volumes:
    prometheus_data: {}
    grafana_data: {}
    im-config_prometheus:
      external: true
    im-config_grafana:
      external: true
    im-config_blackbox:
      external: true

networks:
    front-tier:
        name: internet-monitoring-front-tier
    back-tier:
        name: internet-monitoring-back-tier

services:
    prometheus:
        image: prom/prometheus:latest
        restart: always
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - im-config_prometheus:/etc/prometheus/
            - prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.retention.time=90d'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
            - 9090:9090
        links:
            - ping:ping
            - speedtest:speedtest
        networks:
            - back-tier

    grafana:
        image: grafana/grafana:latest
        restart: always
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - grafana_data:/var/lib/grafana
            - im-config_grafana:/etc/grafana/
        ports:
            - 3030:3000
        networks:
            - back-tier
            - front-tier
        depends_on:
            - prometheus

    ping:
        image: prom/blackbox-exporter:latest
        restart: always
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - im-config_blackbox:/config
        expose:
            - 9115
        ports:
            - 9115:9115
        tty: true
        stdin_open: true
        command:
            - '--config.file=/config/blackbox.yml'
        networks:
            - back-tier

    speedtest:
        image: miguelndecarvalho/speedtest-exporter:latest
        restart: always
        healthcheck:
            test: 'wget --no-verbose --tries=1 --spider http://0.0.0.0:9798/'
            timeout: 10s
        expose:
            - 9798
        ports:
            - 9798:9798
        networks:
            - back-tier

    nodeexp:
        image: prom/node-exporter:latest
        restart: always
        privileged: true
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        ports:
            - 9100:9100
        command:
            - '--path.procfs=/host/proc'
            - '--path.sysfs=/host/sys'
            - --collector.filesystem.ignored-mount-points
            - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
        networks:
            - back-tier
